name: waste_a_gram
description: Take pictures and record all food waste created by your food service.  

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.4
  image_picker: ^0.6.3+4
  flutter_image: ^3.0.0
  shared_preferences: ^0.5.6+2
  firebase_core: ^0.4.4+2
  firebase_storage: ^3.1.3
  cloud_firestore: ^0.13.4+1
  location: ^2.5.4
  cupertino_icons: ^0.1.2
  
  # dev_dependencies:
    # flutter_test:
      # sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/loading.gif
  